webtalk_init -webtalk_dir /home/robertsc/Documents/labDigitales/laboratorio-4-jimenez-sanchez/ej1/project_3.sim/sim_1/behav/xsim/xsim.dir/system_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jul 25 19:23:05 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "70d11fcf-f701-40bd-9c5d-10f7afbc914a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c4ca032f0cb9449e882f9a7d0d184eaa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 3200G with Radeon Vega Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2922.398 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "121172_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2428620944 -regid "" -xml /home/robertsc/Documents/labDigitales/laboratorio-4-jimenez-sanchez/ej1/project_3.sim/sim_1/behav/xsim/xsim.dir/system_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/robertsc/Documents/labDigitales/laboratorio-4-jimenez-sanchez/ej1/project_3.sim/sim_1/behav/xsim/xsim.dir/system_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/robertsc/Documents/labDigitales/laboratorio-4-jimenez-sanchez/ej1/project_3.sim/sim_1/behav/xsim/xsim.dir/system_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
